services:
  backend:
    build:
      context: ./backend    # <--- La carpeta donde está el código del backend
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=qa

  frontend:
    build:
      context: ./schedio-frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=qa
