services:
  backend:
    image: backend-app:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=qa

  frontend:
    image: frontend-app:latest
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=qa
